// Single source of truth for legacy paths that redirect to home.
// Previously duplicated separately in next.config.js and middleware.js —
// kept in one place so the two can never silently drift out of sync.
module.exports = [
  "/pages/timantin-puhtausluokittelu",
  "/products/kukkasormus",
  "/pages/timantin-hiontamuodot",
  "/pages/timantin-vari",
  "/pages/jalometallit-ja-niiden-ominaisuudet",
  "/pages/tietoa-laboratoriossa-valmistetuista-timanteista",
  "/pages/karaattipaino-selitettyna",
  "/pages/timanttikorujen-huolto",
  "/pages/meidan-liike",
  "/pages/milloin-ja-miten-kosia",
  "/pages/timanttitietoutta",
  "/products/kopio-puoliallianssi-sormus-0-33ct-3",
  "/collections/frontpage",
  "/products/timanttikorvakorut",
  "/collections/sileat-kivettomat-sormukset",
  "/products/kopio-kapea-taysallianssisormus-briljanteilla-0-50ct",
  "/collections/sormukset",
  "/products/kopio-kihlasormus-3mm-bombe-court-premium",
  "/products/kopio-kihlasormus-3mm-bombe-court",
  "/pages/nain-tilaat-verkkokaupasta",
  "/products/kopio-kopio-puoliallianssi-sormus-0-33ct",
  "/products/kopio-briljantti-hiontainen-halosormus-yht-0-35ct",
  "/pages/ota-yhteytta",
  "/pages/tilaustyopalvelu",
  "/products/kopio-kihlasormus-4mm-bombe-court-premium",
  "/products/kopio-puoliallianssi-sormus-0-33ct-1",
  "/products/sun-matt-kihlasormus-5-mm",
  "/products/criss-cross-kihlasormus-4-5mm",
  "/products/ice-matt-kihlasormus-4-5-mm-1",
  "/pages/tilaustyot",
  "/pages/koru-opas",
];
