/**
 * ISO 4217 currency metadata (code, name, symbol, country).
 * Used as the canonical list for admin dropdowns and display lookups.
 */
export const CURRENCIES_MASTER = [
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    country: "United Arab Emirates",
    countryCode: "AE",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    country: "Afghanistan",
    countryCode: "AF",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    symbol: "L",
    country: "Albania",
    countryCode: "AL",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "֏",
    country: "Armenia",
    countryCode: "AM",
  },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    symbol: "ƒ",
    country: "Netherlands Antilles",
    countryCode: "NL",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    symbol: "Kz",
    country: "Angola",
    countryCode: "AO",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "$",
    country: "Australia",
    countryCode: "AU",
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    symbol: "ƒ",
    country: "Aruba",
    countryCode: "AW",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    country: "Azerbaijan",
    countryCode: "AZ",
  },
  {
    code: "BAM",
    name: "Bosnia Convertible Mark",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    symbol: "$",
    country: "Barbados",
    countryCode: "BB",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    country: "Bangladesh",
    countryCode: "BD",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    symbol: "лв",
    country: "Bulgaria",
    countryCode: "BG",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: ".د.ب",
    country: "Bahrain",
    countryCode: "BH",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "FBu",
    country: "Burundi",
    countryCode: "BI",
  },
  {
    code: "BMD",
    name: "Bermudan Dollar",
    symbol: "$",
    country: "Bermuda",
    countryCode: "BM",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "$",
    country: "Brunei",
    countryCode: "BN",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "Bs.",
    country: "Bolivia",
    countryCode: "BO",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "$",
    country: "Bahamas",
    countryCode: "BS",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    country: "Bhutan",
    countryCode: "BT",
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    symbol: "P",
    country: "Botswana",
    countryCode: "BW",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "Br",
    country: "Belarus",
    countryCode: "BY",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "$",
    country: "Belize",
    countryCode: "BZ",
  },

  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "$",
    country: "Canada",
    countryCode: "CA",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    country: "Congo",
    countryCode: "CD",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    country: "Switzerland",
    countryCode: "CH",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "$",
    country: "Chile",
    countryCode: "CL",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    country: "China",
    countryCode: "CN",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "$",
    country: "Colombia",
    countryCode: "CO",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    country: "Costa Rica",
    countryCode: "CR",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: "₱",
    country: "Cuba",
    countryCode: "CU",
  },
  {
    code: "CVE",
    name: "Cape Verde Escudo",
    symbol: "$",
    country: "Cape Verde",
    countryCode: "CV",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    country: "Czech Republic",
    countryCode: "CZ",
  },

  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    country: "Denmark",
    countryCode: "DK",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "$",
    country: "Dominican Republic",
    countryCode: "DO",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    symbol: "دج",
    country: "Algeria",
    countryCode: "DZ",
  },

  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "£",
    country: "Egypt",
    countryCode: "EG",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    country: "Ethiopia",
    countryCode: "ET",
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    country: "European Union",
    countryCode: "EU",
  },

  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "$",
    country: "Fiji",
    countryCode: "FJ",
  },

  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    country: "United Kingdom",
    countryCode: "GB",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    country: "Georgia",
    countryCode: "GE",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "₵",
    country: "Ghana",
    countryCode: "GH",
  },

  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "$",
    country: "Hong Kong",
    countryCode: "HK",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    country: "Hungary",
    countryCode: "HU",
  },

  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    country: "Indonesia",
    countryCode: "ID",
  },
  {
    code: "ILS",
    name: "Israeli Shekel",
    symbol: "₪",
    country: "Israel",
    countryCode: "IL",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    country: "India",
    countryCode: "IN",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "ع.د",
    country: "Iraq",
    countryCode: "IQ",
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    symbol: "﷼",
    country: "Iran",
    countryCode: "IR",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    country: "Iceland",
    countryCode: "IS",
  },

  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "$",
    country: "Jamaica",
    countryCode: "JM",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    country: "Japan",
    countryCode: "JP",
  },

  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    country: "Kenya",
    countryCode: "KE",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    country: "South Korea",
    countryCode: "KR",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "د.ك",
    country: "Kuwait",
    countryCode: "KW",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    country: "Kazakhstan",
    countryCode: "KZ",
  },

  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "₨",
    country: "Sri Lanka",
    countryCode: "LK",
  },

  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "د.م.",
    country: "Morocco",
    countryCode: "MA",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    country: "Mexico",
    countryCode: "MX",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    country: "Malaysia",
    countryCode: "MY",
  },

  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    country: "Nigeria",
    countryCode: "NG",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    country: "Norway",
    countryCode: "NO",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "₨",
    country: "Nepal",
    countryCode: "NP",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "$",
    country: "New Zealand",
    countryCode: "NZ",
  },

  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "﷼",
    country: "Oman",
    countryCode: "OM",
  },

  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    country: "Peru",
    countryCode: "PE",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    country: "Philippines",
    countryCode: "PH",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    country: "Pakistan",
    countryCode: "PK",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    country: "Poland",
    countryCode: "PL",
  },

  {
    code: "QAR",
    name: "Qatari Rial",
    symbol: "﷼",
    country: "Qatar",
    countryCode: "QA",
  },

  {
    code: "RON",
    name: "Romanian Leu",
    symbol: "lei",
    country: "Romania",
    countryCode: "RO",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    country: "Russia",
    countryCode: "RU",
  },

  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    country: "Saudi Arabia",
    countryCode: "SA",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "$",
    country: "Singapore",
    countryCode: "SG",
  },

  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    country: "Thailand",
    countryCode: "TH",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    country: "Turkey",
    countryCode: "TR",
  },
  {
    code: "TWD",
    name: "Taiwan Dollar",
    symbol: "NT$",
    country: "Taiwan",
    countryCode: "TW",
  },

  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    code: "USD",
    name: "United States Dollar",
    symbol: "$",
    country: "United States",
    countryCode: "US",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    symbol: "$",
    country: "Uruguay",
    countryCode: "UY",
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "so'm",
    country: "Uzbekistan",
    countryCode: "UZ",
  },

  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    country: "Vietnam",
    countryCode: "VN",
  },

  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    country: "South Africa",
    countryCode: "ZA",
  },
];

/** @type {Record<string, (typeof CURRENCIES_MASTER)[number]>} */
export const CURRENCIES_MASTER_BY_CODE = Object.fromEntries(
  CURRENCIES_MASTER.map((row) => [row.code, row]),
);
